# Generated by Django 4.1.7 on 2023-04-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summoners',
            new_name='Summoner',
        ),
    ]
