# Generated by Django 4.1.7 on 2023-06-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0006_alter_summoner_puuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummonerMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.CharField(max_length=250)),
                ("game_id", models.IntegerField()),
                (
                    "summoner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collector.summoner",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Match",
        ),
        migrations.AddConstraint(
            model_name="summonermatch",
            constraint=models.UniqueConstraint(
                fields=("summoner", "match_id"), name="unique_match"
            ),
        ),
    ]
