# Generated by Django 4.1.7 on 2023-06-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0007_summonermatch_delete_match_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summonermatch",
            name="game_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
