# Generated by Django 4.1.7 on 2023-08-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "game_id",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("game_creation", models.CharField(max_length=250, null=True)),
                ("game_start_timestamp", models.CharField(max_length=250, null=True)),
                ("game_end_timestamp", models.CharField(max_length=250, null=True)),
                ("game_duration", models.CharField(max_length=250, null=True)),
                ("game_mode", models.CharField(max_length=250, null=True)),
                ("game_name", models.CharField(max_length=250, null=True)),
                ("game_type", models.CharField(max_length=250, null=True)),
                ("game_version", models.CharField(max_length=250, null=True)),
                ("map_id", models.IntegerField(null=True)),
                ("platform_id", models.CharField(max_length=250, null=True)),
                ("queue_id", models.IntegerField(null=True)),
                ("teams", models.JSONField(null=True)),
                ("tournament_code", models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatchParticipantBasicStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_position", models.CharField(max_length=200)),
                ("deaths", models.IntegerField()),
                ("assists", models.IntegerField()),
                ("kills", models.IntegerField()),
                ("double_kills", models.IntegerField()),
                ("triple_kills", models.IntegerField()),
                ("quadra_kills", models.IntegerField()),
                ("penta_kills", models.IntegerField()),
                ("first_blood_kill", models.BooleanField()),
                ("first_blood_assist", models.BooleanField()),
                ("first_tower_kill", models.BooleanField()),
                ("first_tower_assist", models.BooleanField()),
                ("largest_multi_kill", models.IntegerField()),
                ("win", models.BooleanField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collector.match",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchParticipantChampionStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("champion_name", models.CharField(max_length=200)),
                ("champ_experience", models.IntegerField()),
                ("champ_level", models.IntegerField()),
                ("items_purchased", models.IntegerField()),
                ("item0", models.IntegerField()),
                ("item1", models.IntegerField()),
                ("item2", models.IntegerField()),
                ("item3", models.IntegerField()),
                ("item4", models.IntegerField()),
                ("item5", models.IntegerField()),
                ("item6", models.IntegerField()),
                ("spell1_casts", models.IntegerField()),
                ("spell2_casts", models.IntegerField()),
                ("spell3_casts", models.IntegerField()),
                ("spell4_casts", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collector.match",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchParticipantStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("champion_name", models.CharField(max_length=250)),
                ("total_damage_dealt", models.IntegerField()),
                ("total_damage_dealt_to_champions", models.IntegerField()),
                ("total_damage_taken", models.IntegerField()),
                ("magic_damage_dealt", models.IntegerField()),
                ("magic_damage_dealt_to_champions", models.IntegerField()),
                ("magic_damage_taken", models.IntegerField()),
                ("physical_damage_dealt", models.IntegerField()),
                ("physical_damage_dealt_to_champions", models.IntegerField()),
                ("physical_damage_taken", models.IntegerField()),
                ("total_heal", models.IntegerField()),
                ("total_minions_killed", models.IntegerField()),
                ("total_time_spent_dead", models.IntegerField()),
                ("true_damage_dealt", models.IntegerField()),
                ("true_damage_dealt_to_champions", models.IntegerField()),
                ("true_damage_taken", models.IntegerField()),
                ("turrent_kills", models.IntegerField()),
                ("turrent_takes", models.IntegerField()),
                ("turrents_lost", models.IntegerField()),
                ("vision_score", models.IntegerField()),
                ("vision_wards_bought_in_game", models.IntegerField()),
                ("wards_killed", models.IntegerField()),
                ("wards_placed", models.IntegerField()),
                ("gold_earned", models.IntegerField()),
                ("gold_spent", models.IntegerField()),
                ("longest_time_spent_living", models.IntegerField()),
                ("time_played", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collector.match",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Summoner",
            fields=[
                (
                    "puuid",
                    models.CharField(
                        editable=False,
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summoner_id", models.CharField(max_length=250)),
                ("account_id", models.CharField(max_length=250)),
                ("name", models.CharField(max_length=250, unique=True)),
                ("profile_icon_id", models.CharField(max_length=250)),
                ("revision_date", models.DateTimeField()),
                ("summoner_level", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SummonerMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.CharField(max_length=250)),
                (
                    "game",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collector.match",
                    ),
                ),
                (
                    "summoner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collector.summoner",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Summoners",
        ),
        migrations.AddField(
            model_name="matchparticipantstats",
            name="summoner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="collector.summoner"
            ),
        ),
        migrations.AddField(
            model_name="matchparticipantchampionstats",
            name="summoner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="collector.summoner"
            ),
        ),
        migrations.AddField(
            model_name="matchparticipantbasicstats",
            name="summoner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="collector.summoner"
            ),
        ),
        migrations.AddConstraint(
            model_name="summonermatch",
            constraint=models.UniqueConstraint(
                fields=("summoner", "match_id"), name="unique_match"
            ),
        ),
    ]
