# Generated by Django 4.1.7 on 2023-08-15 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0002_match_matchparticipantbasicstats_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchparticipantstats",
            old_name="turrent_kills",
            new_name="turret_kills",
        ),
        migrations.RenameField(
            model_name="matchparticipantstats",
            old_name="turrent_takes",
            new_name="turret_takedowns",
        ),
        migrations.RenameField(
            model_name="matchparticipantstats",
            old_name="turrents_lost",
            new_name="turrets_lost",
        ),
    ]
