# Generated by Django 4.1.7 on 2023-04-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0003_alter_summoner_name_alter_summoner_summoner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summoner",
            name="summoner_id",
            field=models.CharField(max_length=250),
        ),
    ]
