# Generated by Django 4.1.7 on 2023-06-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0008_alter_summonermatch_game_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summonermatch",
            name="game_id",
            field=models.CharField(max_length=10),
        ),
    ]
