# Generated by Django 4.1.7 on 2023-08-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0012_matchparticipantchampionstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="game_duration",
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="match",
            name="game_creation",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="match",
            name="game_end_timestamp",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="match",
            name="game_start_timestamp",
            field=models.CharField(max_length=250),
        ),
    ]
