@startuml
entity  Summoner{
 + puuid
 + summoner_id
 + account_id
 + name
 + profile_icon_id
 + revision_date
 + summoner_level
}

entity SummonerMatch{
 + id
 + puuid
 + game_id
}

entity Match{
 + game_id
 + game_creation
 + game_start_timestamp
 + game_end_timestamp
 + game_duration
 + game_mode
 + game_name
 + game_type
 + game_version
 + map_id
 + platform_id
 + queue_id
 + teams
 + tournament_code
}

entity MatchParticipantBasicStats{
 + summoner_match_id
 + game_id
 + summoner_name
 + team_position
 + deaths
 + assists
 + kills
 + double_kills
 + triple_kills
 + quadra_kills
 + penta_kills
 + first_blood_kill
 + first_blood_assist
 + first_tower_kill
 + first_tower_assist
 + largest_multi_kill
 + win
}

entity MatchParticipantChampionStats{
 + summoner_match_id
 + game_id
 + champion_name
 + champ_experience
 + champ_level
 + items_purchased
 + item0
 + item1
 + item2
 + item3
 + item4
 + item5
 + item6
 + spell1_casts
 + spell2_casts
 + spell3_casts
 + spell4_casts
}

entity MatchParticipantStats{
 + summoner_match_id
 + game_id
 + champion_name
 + total_damage_dealt
 + total_damage_dealt_to_champions
 + total_damage_taken
 + magic_damage_dealt
 + magic_damage_dealt_to_champions
 + magic_damage_taken
 + physical_damage_dealt
 + physical_damage_dealt_to_champions
 + physical_damage_taken
 + total_heal
 + total_minions_killed
 + total_time_spent_dead
 + true_damage_dealt
 + true_damage_dealt_to_champions
 + true_damage_taken
 + turrent_kills
 + turrent_takes
 + turrents_lost
 + vision_score
 + vision_wards_bought_in_game
 + wards_killed
 + wards_placed
 + gold_earned
 + gold_spent
 + longest_time_spent_living
 + time_played
}

Summoner .. SummonerMatch
SummonerMatch .. Match
SummonerMatch .. MatchParticipantBasicStats
SummonerMatch .. MatchParticipantStats
SummonerMatch .. MatchParticipantChampionStats
Match .. MatchParticipantBasicStats
Match .. MatchParticipantStats
Match .. MatchParticipantChampionStats
@enduml