name: Format code
on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Cormat code 
        run: black .
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Git Actions
          message: 'Lint code'
          add: '*.py'